src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("user")]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique:true)]
    #[Assert\Email(message:"email format invalide")]
    #[Assert\NotBlank(message:"L'email est obligatoire")]
    #[Groups("user")]
    private ?string $email = null;

    #[ORM\Column]
    #[Groups("user")]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Groups("user")]
    private ?string $password = null;

    #[ORM\Column]
    #[Assert\Length(min:8, max:8)]
    #[Groups("user")]
    private ?int $num_tel = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:3, max:70)]
    #[Groups("user")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:3, max:70)]
    #[Groups("user")]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("user")]
    private ?\DateTimeInterface $date_naissance = null;
    
    #[ORM\Column(length: 255, unique:true)]
    #[Assert\Length(min:3, max:70)]
    #[Assert\NotBlank(message:"Le nom utilisateur est obligatoire")]
    #[Groups("user")]
    private ?string $username = null;

    #[ORM\Column(type: 'boolean')]
    #[Groups("user")]
    private $isVerified = false;

    #[ORM\Column]
    #[Groups("user")]
    private ?bool $is_Banned = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(int $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function __toString()
    {
        return $this->username;
    }

    public function isIsBanned(): ?bool
    {
        return $this->is_Banned;
    }

    public function setIsBanned(bool $is_Banned): self
    {
        $this->is_Banned = $is_Banned;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('username')
            ->add('nom')
            ->add('prenom')
            /*->add('plainPassword', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'label' => 'Password',
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                    new Assert\Regex([
                        'pattern' => '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*$/',
                        'message' => 'Your password should contain at least one lowercase letter, one uppercase letter and one number',
                    ]),
                ],
            ])*/
            ->add('num_tel',NumberType::class,[
                'label' => 'Numero du telephone',
            ])
            ->add('date_naissance',DateType::class,[
                'widget'=>'single_text',
                'format'=>'yyyy-MM-dd'
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository,UserPasswordHasherInterface $userPasswordHasher): Response

    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plainPassword=$form->get('plainPassword')->getData();
            $hashPassword=$userPasswordHasher->hashPassword($user,$plainPassword);
            $user->setPassword($hashPassword);

            $user->setRoles(['ROLE_GAMER']);

            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index');
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository,UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plainPassword=$form->get('plainPassword')->getData();
            $hashPassword=$userPasswordHasher->hashPassword($user,$plainPassword);
            $user->setPassword($hashPassword);

            $user->setRoles(['ROLE_GAMER']);
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/ban', name: 'app_ban')]
    public function setPostToActive(UserRepository $userRepository,$id,ManagerRegistry $mg)
    {
        $user=$userRepository->find($id);
    
        if ($user->isIsBanned())
            $user->setIsBanned(false);
        else
            $user->setIsBanned(true);
        $sem=$mg->getManager();
        $sem-> persist($user);
        $sem->flush();
        return $this->redirectToRoute('app_user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
 {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Ajouter Gamer
{% endblock %}

{% block body %}
	<div class="container">
		<h2 class="text-center mt-5 mb-3">Liste des catégories</h2>
		<div class="card">
			<div class="card-header">
				<h1>Editer un utilisateur</h1>
			</div>
			<div class="card-body" style="overflow-y:auto;height:400px;display:fixe">
				{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

				<a href="{{ path('app_user_index') }}">back to list</a>

				{{ include('user/_delete_form.html.twig') }}</div>
		</div>
	</div>

{% endblock %}

templates/user/index.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Liste des Gamers{% endblock %}

{% block body %}
	<div class="container">
		<h2 class="text-center mt-5 mb-3">Liste des gamers</h2>
		<div class="card">
			{#<div class="card-header">
				<a class="btn btn-outline-primary" href="{{ path('app_user_new') }}">
					Ajouter Gamer
				</a>
			</div>#}
			<div class="card-body" style="overflow-x:auto;overflow-y:auto;height:400px;display:fixe">
				<table id="example" class="table table-striped table-bordered" >
					<thead>
						<tr>
							<th>Email</th>
							<th>Username</th>
							<th>Nom</th>
							<th>Prenom</th>
							<th>Num_tel</th>
							<th>Date_naissance</th>
							<th>Statut</th>
							<th>Bloqué</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for user in users %}
							{% if 'ROLE_GAMER' in user.roles %}
							<tr>
								<td>{{ user.email }}</td>
								<td>{{ user.username }}</td>
								<td>{{ user.nom }}</td>
								<td>{{ user.prenom }}</td>
								<td>{{ user.numTel }}</td>
								<td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
								<td>
									{% if user.isBanned == false %}
										<span class="badge badge-secondary">active</span>
									{% else %}
										<span class="badge badge-danger">Bloqué</span>
									{% endif %}
								</td>
								<td>
									<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
										<div class="buttons-preview">
											{% if user.isBanned %}
												<a href="{{ path('app_ban', {'id':user.id}) }}" class="btn btn-success">Activé</a>
											{% else %}
												<a href="{{ path('app_ban', {'id':user.id}) }}" class="btn btn-danger">Bloqué</a>
											{% endif %}
										</div>
								</td>
								<td>
                                    <a href="{{ path('app_user_show', {'id': user.id}) }}">
										<button class='btn'><i class="fa fa-eye" style="color:white;"></i></button>
									</a>
									{#<a href="{{ path('app_user_edit', {'id': user.id}) }}">
										<button class='btn'><i class="fa fa-edit" style="color:white;"></i></button>
									</a>#}
									<a href="{{ path('app_user_delete', {'id': user.id}) }}">
										<button class="btn"><i class="fa fa-trash" style="color:white;"></i></button>
									</a>
								</td>
							</tr>
							{% endif %}
						{% else %}
							<tr>
								<td colspan="10">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock %}

templates/user/new.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Ajouter Gamer
{% endblock %}

{% block body %}
	<div class="container">
		<h2 class="text-center mt-5 mb-3">Liste des catégories</h2>
		<div class="card">
			<div class="card-header">
				<h1>Créer un nouveau utilisateur</h1>
			</div>
			<div class="card-body" style="overflow-y:auto;height:400px;display:fixe">
				{{ include('user/_form.html.twig') }}
				<a class="btn btn-outline-primary" href="{{ path('app_user_index') }}">back to list</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Liste des Gamers
{% endblock %}

{% block body %}
	<div class="container">
		<h2 class="text-center mt-5 mb-3">{{user.username}}</h2>
		<div class="card">
			<div class="card-header">
				<h1>Consulter utilisateur</h1>
			</div>
			<div class="card-body" style="overflow-x:auto;overflow-y:auto;height:400px;display:fixe">
				<table class="table">
					<tbody>
						<tr>
							<th>Email</th>
							<td>{{ user.email }}</td>
						</tr>
						<tr>
							<th>Username</th>
							<td>{{ user.username }}</td>
						</tr>
						<tr>
							<th>Nom</th>
							<td>{{ user.nom }}</td>
						</tr>
						<tr>
							<th>Prenom</th>
							<td>{{ user.prenom }}</td>
						</tr>
						<tr>
							<th>Numero telephone</th>
							<td>{{ user.numTel }}</td>
						</tr>
						<tr>
							<th>Date_naissance</th>
							<td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
						</tr>
					</tbody>
				</table>

				<a class="btn btn-outline-primary" href="{{ path('app_user_index') }}">back to list</a>

				<a class="btn btn-outline-primary" href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

				<a class="btn btn-outline-danger" style="color:white">{{ include('user/_delete_form.html.twig') }}</a>
			</div>
		</div>
	</div>
{% endblock %}